on:
  push:
    #branches: [master]
  pull_request:

name: CI

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          components: rustfmt
      - uses: actions-rs/cargo@v1
        name: "Build"
        with:
          command: build
      - uses: actions-rs/cargo@v1
        name: "cargo fmt"
        with:
          command: fmt
          args: -- --check
